[2022-06-27 20:13:30,289] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\HPr\\Documents\\project\\Ml_Projekt\\housing\\artifact')
[2022-06-27 20:13:30,290] root - INFO - ====================Data Ingestion log started.==================== 
[2022-06-27 20:13:30,290] root - ERROR - 
        Error occured in script: 
        [ C:\Users\HPr\Documents\project\Ml_Projekt\housing\pipeline\pipeline.py ] at 
        try block line number: [46] and exception block line number: [52] 
        error message: [
        Error occured in script: 
        [ C:\Users\HPr\Documents\project\Ml_Projekt\housing\pipeline\pipeline.py ] at 
        try block line number: [22] and exception block line number: [24] 
        error message: [
        Error occured in script: 
        [ C:\Users\HPr\Documents\project\Ml_Projekt\housing\component\data_ingestion.py ] at 
        try block line number: [124] and exception block line number: [128] 
        error message: [
        Error occured in script: 
        [ C:\Users\HPr\Documents\project\Ml_Projekt\housing\component\data_ingestion.py ] at 
        try block line number: [26] and exception block line number: [46] 
        error message: ['function' object has no attribute 'dataset_download_url']
        ]
        ]
        ]
        
[2022-06-27 20:13:30,294] root - INFO - ====================Data Ingestion log completed.==================== 


